### ISSUE TITLE
simulations not working in Drone project

### ISSUE THREAD

**Issue by mariaBer** [citros-garden/drone#65]
citros run not woring for Simulations:
simulation_sensor_combined_listener
simulation_simulation

 **Describe the bug**

**To Reproduce**
1. Go to project
2. write citros run and run the simulation mentioned above
3. See error

**Expected behavior**
simulation runs and data is written

**Comment by iftahnaf** [comment]
Hi @mariaBer,

Those launch files are for development (`simulation.launch.py`) or comes with dependency package (`sensor_combined_listener`) so they are not supposed to run.

We can add this note in the CITROS's tutorial documentation.

**Comment by mariaBer** [comment]
Got it, thanks
